### ISSUE TITLE
prestige button not working

### ISSUE THREAD

**Issue by 123mind123** [Tondorian/StardewValleyMods#1]
Got this error when pressing the prestige button in the skill menu:

[Skill Prestige] This mod failed in the Input.ButtonPressed event. Technical details:
InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at SkillPrestige.Framework.Menus.SkillsMenuExtension.OpenPrestigeMenu(Skill skill) in E:\Personal Files\Git Repos\SkillPrestige\SkillPrestige\Framework\Menus\SkillsMenuExtension.cs:line 151
   at SkillPrestige.Framework.Menus.SkillsMenuExtension.<>c__DisplayClass6_0.<IntializeSkillsMenu>b__0() in E:\Personal Files\Git Repos\SkillPrestige\SkillPrestige\Framework\Menus\SkillsMenuExtension.cs:line 97
   at SkillPrestige.Framework.Menus.Elements.Buttons.TextureButton.OnButtonPressed(ButtonPressedEventArgs e, Boolean isClick) in E:\Personal Files\Git Repos\SkillPrestige\SkillPrestige\Framework\Menus\Elements\Buttons\TextureButton.cs:line 52
   at SkillPrestige.Framework.Menus.SkillsMenuExtension.OnButtonPressed(ButtonPressedEventArgs e, Boolean isClick) in E:\Personal Files\Git Repos\SkillPrestige\SkillPrestige\Framework\Menus\SkillsMenuExtension.cs:line 42
   at SkillPrestige.ModEntry.OnButtonPressed(Object sender, ButtonPressedEventArgs e) in E:\Personal Files\Git Repos\SkillPrestige\SkillPrestige\ModEntry.cs:line 90
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101

**Comment by Tondorian** [comment]
thank you for your report,
 did you test it on a new savegame or an existing one? 
 Do you use one ore both of the luck and magic prestige extensions? 
 If you use an existing save can you provide it to me?
 I guess the issue is related to how the skill prestige Basemod manage to check if a skill is the right one

**Comment by 123mind123** [comment]
A totally new save with just the magic and the magic prestige mod found here https://forums.stardewvalley.net/threads/unofficial-mod-updates.2096/page-27#post-23768.
